2024-05-31 00:13:20,668 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:13:20,670 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/ZFgNy1KCU6
2024-05-31 00:13:20,670 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:13:20,670 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/ZFgNy1KCU6
2024-05-31 00:13:20,670 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:13:20,670 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:13:21,166 - flet_runtime - INFO - App session started
2024-05-31 00:13:49,059 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:13:54,628 - __main__ - INFO - User 'admin' created project 'vfdk' with ID '1e604479-e114-4bc9-bb00-9791d2b7fb3a'.
2024-05-31 00:13:54,631 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 00:13:54,634 - __main__ - INFO - User 'admin' viewed project 'vfdk'.
2024-05-31 00:13:55,776 - __main__ - INFO - User 'admin' viewed project members for project ID '1e604479-e114-4bc9-bb00-9791d2b7fb3a'.
2024-05-31 00:13:58,012 - __main__ - INFO - User 'lilia' removed from project '1e604479-e114-4bc9-bb00-9791d2b7fb3a' by user 'admin'.
2024-05-31 00:14:02,224 - __main__ - INFO - User 'kei1' added to project '1e604479-e114-4bc9-bb00-9791d2b7fb3a' by user 'admin'.
2024-05-31 00:14:04,625 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=IntegrityError('UNIQUE constraint failed: project_members.project_id, project_members.user_id')>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1907, in add_members
    self.db.add_project_member(self.project_id, user_id)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/database.py", line 305, in add_project_member
    self.conn.execute(query, (project_id, member_id))
sqlite3.IntegrityError: UNIQUE constraint failed: project_members.project_id, project_members.user_id
2024-05-31 00:14:10,028 - __main__ - INFO - User 'admin' viewed project 'vfdk'.
2024-05-31 00:14:11,108 - __main__ - INFO - User 'admin' viewed tasks for project ID '1e604479-e114-4bc9-bb00-9791d2b7fb3a'.
2024-05-31 00:14:12,011 - __main__ - INFO - User 'admin' viewed project 'vfdk'.
2024-05-31 00:14:13,739 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:14:15,076 - __main__ - INFO - User 'admin' viewed project 'efoiudesf'.
2024-05-31 00:14:16,626 - __main__ - INFO - User 'admin' viewed tasks for project ID '9a5f7159-879e-48f7-aeaf-e970d8cb2e47'.
2024-05-31 00:14:17,943 - __main__ - INFO - User 'admin' viewed details of task ID '7f4fc932-6010-4d3f-bf3f-ef67236309b4'.
2024-05-31 00:14:21,146 - __main__ - INFO - User 'admin' viewed project 'efoiudesf'.
2024-05-31 00:14:27,310 - __main__ - INFO - User 'admin' viewed tasks for project ID '9a5f7159-879e-48f7-aeaf-e970d8cb2e47'.
2024-05-31 00:14:29,861 - __main__ - INFO - User 'admin' viewed project 'efoiudesf'.
2024-05-31 00:14:34,723 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:14:35,491 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:16:33,805 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:16:34,942 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:28:11,070 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:28:11,071 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/l29MrzIozI
2024-05-31 00:28:11,071 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:28:11,071 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/l29MrzIozI
2024-05-31 00:28:11,071 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:28:11,071 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:28:11,274 - flet_runtime - INFO - App session started
2024-05-31 00:28:20,923 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:28:22,454 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:28:23,225 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:30:38,225 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:30:38,226 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/hJmhR95NmN
2024-05-31 00:30:38,226 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:30:38,226 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/hJmhR95NmN
2024-05-31 00:30:38,226 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:30:38,226 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:30:38,428 - flet_runtime - INFO - App session started
2024-05-31 00:30:44,340 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:30:45,625 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:30:46,575 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:32:18,913 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:32:18,914 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/EdGIHk2cmR
2024-05-31 00:32:18,914 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:32:18,914 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/EdGIHk2cmR
2024-05-31 00:32:18,914 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:32:18,914 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:32:19,138 - flet_runtime - INFO - App session started
2024-05-31 00:32:24,789 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:32:26,173 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:32:26,726 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:32:54,105 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:32:54,105 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/9fCjWOADCr
2024-05-31 00:32:54,105 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:32:54,105 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/9fCjWOADCr
2024-05-31 00:32:54,105 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:32:54,106 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:32:54,292 - flet_runtime - INFO - App session started
2024-05-31 00:32:59,539 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:33:00,657 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:33:01,592 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:39:31,548 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:39:31,548 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/F4PLQUjdNg
2024-05-31 00:39:31,549 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:39:31,549 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/F4PLQUjdNg
2024-05-31 00:39:31,549 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:39:31,549 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:39:32,029 - flet_runtime - INFO - App session started
2024-05-31 00:39:37,491 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:39:39,174 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:39:39,793 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:39:39,794 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'mappingproxy' object has no attribute '__dict__'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 419, in <lambda>
    on_click=lambda e, project_id=project.get_project_id(): self.manage_project(project_id),
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 487, in manage_project
    self.page.update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 324, in update
    r = self.__update(self)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 426, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 439, in __prepare_update
    control.build_update_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 454, in build_update_commands
    innerCmds = ctrl._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 512, in _build_add_commands
    command = self._build_command(False)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 541, in _build_command
    self.before_update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/container.py", line 208, in before_update
    self._set_attr_json("alignment", self.__alignment)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 140, in _set_attr_json
    nv = self._convert_attr_json(value)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 146, in _convert_attr_json
    json.dumps(value, cls=EmbedJsonEncoder, separators=(",", ":"))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 43, in encode
    return super().encode(self._convert_enums(o))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 40, in default
    return self._convert_enums(obj.__dict__)
AttributeError: 'mappingproxy' object has no attribute '__dict__'
2024-05-31 00:39:40,509 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:39:40,510 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'mappingproxy' object has no attribute '__dict__'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 419, in <lambda>
    on_click=lambda e, project_id=project.get_project_id(): self.manage_project(project_id),
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 487, in manage_project
    self.page.update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 324, in update
    r = self.__update(self)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 426, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 439, in __prepare_update
    control.build_update_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 454, in build_update_commands
    innerCmds = ctrl._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 512, in _build_add_commands
    command = self._build_command(False)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 541, in _build_command
    self.before_update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/container.py", line 208, in before_update
    self._set_attr_json("alignment", self.__alignment)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 140, in _set_attr_json
    nv = self._convert_attr_json(value)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 146, in _convert_attr_json
    json.dumps(value, cls=EmbedJsonEncoder, separators=(",", ":"))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 43, in encode
    return super().encode(self._convert_enums(o))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 40, in default
    return self._convert_enums(obj.__dict__)
AttributeError: 'mappingproxy' object has no attribute '__dict__'
2024-05-31 00:51:30,452 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 00:51:30,457 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'mappingproxy' object has no attribute '__dict__'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 461, in <lambda>
    on_click=lambda e: self.page.go("/main"),
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 560, in go
    self.update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 324, in update
    r = self.__update(self)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 426, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 439, in __prepare_update
    control.build_update_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 454, in build_update_commands
    innerCmds = ctrl._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 523, in _build_add_commands
    childCmd = control._build_add_commands(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 512, in _build_add_commands
    command = self._build_command(False)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 541, in _build_command
    self.before_update()
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/container.py", line 208, in before_update
    self._set_attr_json("alignment", self.__alignment)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 140, in _set_attr_json
    nv = self._convert_attr_json(value)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/control.py", line 146, in _convert_attr_json
    json.dumps(value, cls=EmbedJsonEncoder, separators=(",", ":"))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 43, in encode
    return super().encode(self._convert_enums(o))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/embed_json_encoder.py", line 40, in default
    return self._convert_enums(obj.__dict__)
AttributeError: 'mappingproxy' object has no attribute '__dict__'
2024-05-31 00:51:35,235 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:51:35,236 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/qhmwlIDw1c
2024-05-31 00:51:35,236 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:51:35,236 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/qhmwlIDw1c
2024-05-31 00:51:35,236 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:51:35,236 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:51:35,667 - flet_runtime - INFO - App session started
2024-05-31 00:54:23,992 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:54:25,210 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:54:26,512 - __main__ - INFO - User 'admin' viewed project 'dsd'.
2024-05-31 00:54:29,127 - __main__ - INFO - User 'admin' initiated adding a task for project ID 'b383e767-fe9e-4154-812c-992296c2d491'.
2024-05-31 00:54:41,049 - __main__ - INFO - New task 'fgv' added to project b383e767-fe9e-4154-812c-992296c2d491 by user 'admin'.
2024-05-31 00:54:41,051 - __main__ - INFO - User lilia assigned to task 'fgv' by user 'admin'.
2024-05-31 00:54:41,058 - __main__ - INFO - User 'admin' viewed project 'dsd'.
2024-05-31 00:54:42,427 - __main__ - INFO - User 'admin' viewed tasks for project ID 'b383e767-fe9e-4154-812c-992296c2d491'.
2024-05-31 00:54:43,512 - __main__ - INFO - User 'admin' viewed details of task ID '1235a634-a65a-4c90-9ac0-fa92accd8d5d'.
2024-05-31 00:54:47,510 - __main__ - INFO - User 'admin' viewed comments for task ID '1235a634-a65a-4c90-9ac0-fa92accd8d5d'.
2024-05-31 00:54:49,754 - __main__ - INFO - User 'admin' added the comment 'vb df' to task ID '1235a634-a65a-4c90-9ac0-fa92accd8d5d'.
2024-05-31 00:54:52,110 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'session'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1375, in add_comment
    username = self.db.get_current_user_username(self.page)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/database.py", line 294, in get_current_user_username
    username = page.session.get("username")
AttributeError: 'NoneType' object has no attribute 'session'
2024-05-31 00:54:53,094 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'session'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1375, in add_comment
    username = self.db.get_current_user_username(self.page)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/database.py", line 294, in get_current_user_username
    username = page.session.get("username")
AttributeError: 'NoneType' object has no attribute 'session'
2024-05-31 00:54:55,176 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:54:55,878 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:55:00,011 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:55:00,012 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/ibF5l06yML
2024-05-31 00:55:00,012 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:55:00,012 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/ibF5l06yML
2024-05-31 00:55:00,012 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:55:00,012 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:55:00,233 - flet_runtime - INFO - App session started
2024-05-31 00:56:16,942 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:56:23,870 - __main__ - INFO - User 'admin' created project 'fgvs' with ID 'fa3bfcb2-c436-4a83-9611-4267c465cc2d'.
2024-05-31 00:56:23,874 - __main__ - INFO - User 'admin' viewed project 'fgvs'.
2024-05-31 00:56:23,877 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 00:56:25,045 - __main__ - INFO - User 'admin' viewed tasks for project ID 'fa3bfcb2-c436-4a83-9611-4267c465cc2d'.
2024-05-31 00:56:25,946 - __main__ - INFO - User 'admin' viewed project 'fgvs'.
2024-05-31 00:56:26,680 - __main__ - INFO - User 'admin' initiated adding a task for project ID 'fa3bfcb2-c436-4a83-9611-4267c465cc2d'.
2024-05-31 00:56:37,681 - __main__ - INFO - New task 'vb' added to project fa3bfcb2-c436-4a83-9611-4267c465cc2d by user 'admin'.
2024-05-31 00:56:37,689 - __main__ - INFO - User 'admin' viewed project 'fgvs'.
2024-05-31 00:56:38,980 - __main__ - INFO - User 'admin' viewed tasks for project ID 'fa3bfcb2-c436-4a83-9611-4267c465cc2d'.
2024-05-31 00:56:40,029 - __main__ - INFO - User 'admin' viewed details of task ID 'a48c11b6-8006-4534-995b-b2f8a16bdad1'.
2024-05-31 00:56:42,045 - __main__ - INFO - User 'admin' viewed history for task ID 'a48c11b6-8006-4534-995b-b2f8a16bdad1'.
2024-05-31 00:56:49,398 - __main__ - INFO - User 'admin' viewed project 'fgvs'.
2024-05-31 00:57:23,893 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:57:28,111 - __main__ - INFO - User 'admin' viewed project 'jndcv'.
2024-05-31 00:58:04,060 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:58:10,752 - __main__ - INFO - User 'admin' created project 'vfsfv' with ID '8bbea63c-4b64-406a-be26-6e9f2c618b44'.
2024-05-31 00:58:10,753 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 00:58:10,758 - __main__ - INFO - User 'admin' viewed project 'vfsfv'.
2024-05-31 00:58:12,911 - __main__ - INFO - User 'admin' initiated adding a task for project ID '8bbea63c-4b64-406a-be26-6e9f2c618b44'.
2024-05-31 00:58:25,214 - __main__ - INFO - New task 'fvsdfv' added to project 8bbea63c-4b64-406a-be26-6e9f2c618b44 by user 'admin'.
2024-05-31 00:58:25,215 - __main__ - INFO - User admin assigned to task 'fvsdfv' by user 'admin'.
2024-05-31 00:58:25,221 - __main__ - INFO - User 'admin' viewed project 'vfsfv'.
2024-05-31 00:58:26,561 - __main__ - INFO - User 'admin' viewed tasks for project ID '8bbea63c-4b64-406a-be26-6e9f2c618b44'.
2024-05-31 00:58:27,510 - __main__ - INFO - User 'admin' viewed details of task ID '0fe2cf3c-d646-48e3-94c0-aadf251ab41e'.
2024-05-31 00:58:31,997 - __main__ - INFO - User 'admin' viewed details of task ID '0fe2cf3c-d646-48e3-94c0-aadf251ab41e'.
2024-05-31 00:58:32,996 - __main__ - INFO - User 'admin' viewed comments for task ID '0fe2cf3c-d646-48e3-94c0-aadf251ab41e'.
2024-05-31 00:58:36,899 - __main__ - INFO - User 'admin' added the comment 'sdfd' to task ID '0fe2cf3c-d646-48e3-94c0-aadf251ab41e'.
2024-05-31 00:58:37,978 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:58:39,210 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:58:39,611 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:58:39,778 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'go'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 1402, in <lambda>
    on_click=lambda e: self.page.go(f"/show_task_details/{self.task_id}"),
AttributeError: 'NoneType' object has no attribute 'go'
2024-05-31 00:58:43,498 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 00:58:43,498 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/53x3HeGVj4
2024-05-31 00:58:43,499 - flet_runtime - INFO - Flet app has started...
2024-05-31 00:58:43,499 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/53x3HeGVj4
2024-05-31 00:58:43,499 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 00:58:43,499 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 00:58:43,732 - flet_runtime - INFO - App session started
2024-05-31 00:58:50,478 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 00:58:59,683 - __main__ - INFO - User 'admin' created project 'vbzdf' with ID 'dfvbsf'.
2024-05-31 00:58:59,686 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 00:58:59,689 - __main__ - INFO - User 'admin' viewed project 'vbzdf'.
2024-05-31 00:59:01,879 - __main__ - INFO - User 'admin' viewed tasks for project ID 'dfvbsf'.
2024-05-31 00:59:03,117 - __main__ - INFO - User 'admin' viewed project 'vbzdf'.
2024-05-31 00:59:06,577 - __main__ - INFO - User admin requested to see their projects
2024-05-31 00:59:09,646 - __main__ - INFO - User 'admin' viewed project 'hi'.
2024-05-31 00:59:11,563 - __main__ - INFO - User 'admin' viewed tasks for project ID 'b8d5e7ab-f75f-4305-b9b8-373935549d5a'.
2024-05-31 00:59:13,367 - __main__ - INFO - User 'admin' viewed project 'hi'.
2024-05-31 01:15:00,630 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 01:15:00,631 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/UyJYnQFaMb
2024-05-31 01:15:00,631 - flet_runtime - INFO - Flet app has started...
2024-05-31 01:15:00,631 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/UyJYnQFaMb
2024-05-31 01:15:00,631 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 01:15:00,631 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 01:15:01,119 - flet_runtime - INFO - App session started
2024-05-31 01:15:06,982 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:15:12,720 - __main__ - INFO - User 'admin' created project 'uiozdhfcd' with ID 'b8ba718c-7d82-411d-95ac-af08f5026676'.
2024-05-31 01:15:12,723 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 01:15:12,726 - __main__ - INFO - User 'admin' viewed project 'uiozdhfcd'.
2024-05-31 01:16:49,960 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 01:16:49,964 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/D7aXpPfAiS
2024-05-31 01:16:49,964 - flet_runtime - INFO - Flet app has started...
2024-05-31 01:16:49,964 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/D7aXpPfAiS
2024-05-31 01:16:49,964 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 01:16:49,964 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 01:16:50,274 - flet_runtime - INFO - App session started
2024-05-31 01:16:56,117 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:16:57,650 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:16:58,267 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:17:08,400 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:17:23,075 - __main__ - INFO - User 'admin' created project 'dfnd' with ID '4a09ea2d-e39f-4622-b1b1-3f448e322926'.
2024-05-31 01:17:23,079 - __main__ - INFO - User 'admin' viewed project 'dfnd'.
2024-05-31 01:17:23,079 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_usernames' is not defined")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 828, in create_project_confirm
    for username in selected_usernames:
NameError: name 'selected_usernames' is not defined
2024-05-31 01:17:25,339 - __main__ - INFO - User 'admin' viewed project members for project ID '4a09ea2d-e39f-4622-b1b1-3f448e322926'.
2024-05-31 01:17:26,705 - __main__ - INFO - User 'admin' viewed project 'dfnd'.
2024-05-31 01:17:28,738 - __main__ - INFO - User 'admin' viewed tasks for project ID '4a09ea2d-e39f-4622-b1b1-3f448e322926'.
2024-05-31 01:17:29,522 - __main__ - INFO - User 'admin' viewed project 'dfnd'.
2024-05-31 01:17:31,332 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:17:32,518 - __main__ - INFO - User 'admin' viewed project 'final test'.
2024-05-31 01:18:01,204 - __main__ - INFO - User 'admin' viewed tasks for project ID '9d9cdade-522c-40b0-acf3-13b65a7c1d2d'.
2024-05-31 01:18:03,924 - __main__ - INFO - User 'admin' viewed project 'final test'.
2024-05-31 01:19:45,868 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:19:47,850 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:19:54,670 - __main__ - INFO - User 'admin' viewed project 'uiozdhfcd'.
2024-05-31 01:25:15,939 - __main__ - WARNING - Invalid login attempt for user: asmin
2024-05-31 01:25:16,904 - __main__ - WARNING - Invalid login attempt for user: asmin
2024-05-31 01:25:21,020 - __main__ - WARNING - Invalid login attempt for user: admin
2024-05-31 01:25:25,004 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:25:53,803 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:26:14,538 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:26:15,572 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:26:17,390 - __main__ - INFO - User 'admin' viewed tasks for project ID '1d56622c-de61-4461-a869-c7d377f1704d'.
2024-05-31 01:26:31,008 - __main__ - INFO - User 'admin' viewed details of task ID '635ec015-9778-4a8d-897c-745909565113'.
2024-05-31 01:26:33,106 - __main__ - INFO - User 'admin' viewed comments for task ID '635ec015-9778-4a8d-897c-745909565113'.
2024-05-31 01:26:35,923 - __main__ - INFO - User 'admin' viewed history for task ID '635ec015-9778-4a8d-897c-745909565113'.
2024-05-31 01:27:17,893 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:27:20,023 - __main__ - INFO - User 'admin' viewed tasks for project ID '1d56622c-de61-4461-a869-c7d377f1704d'.
2024-05-31 01:27:21,344 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:27:24,541 - __main__ - INFO - User 'admin' initiated adding a task for project ID '1d56622c-de61-4461-a869-c7d377f1704d'.
2024-05-31 01:27:27,495 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:27:46,089 - __main__ - WARNING - Invalid login attempt for user: admin
2024-05-31 01:37:57,109 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 01:37:57,110 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/6To4RGQDmk
2024-05-31 01:37:57,110 - flet_runtime - INFO - Flet app has started...
2024-05-31 01:37:57,110 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/6To4RGQDmk
2024-05-31 01:37:57,110 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 01:37:57,110 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 01:37:57,340 - flet_runtime - INFO - App session started
2024-05-31 01:38:04,328 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:38:05,661 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:38:06,396 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:38:13,629 - __main__ - INFO - User 'admin' viewed tasks for project ID '1d56622c-de61-4461-a869-c7d377f1704d'.
2024-05-31 01:38:15,699 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:41:40,068 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 01:41:40,069 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/dpG5kB1xt8
2024-05-31 01:41:40,069 - flet_runtime - INFO - Flet app has started...
2024-05-31 01:41:40,069 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/dpG5kB1xt8
2024-05-31 01:41:40,069 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 01:41:40,069 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 01:41:40,372 - flet_runtime - INFO - App session started
2024-05-31 01:41:45,865 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:41:47,097 - __main__ - INFO - User admin requested to see their projects
2024-05-31 01:41:48,100 - __main__ - INFO - User 'admin' viewed project 'test'.
2024-05-31 01:43:24,134 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'CreateProjectPage' object has no attribute 'logger'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 898, in cancel_dialog
    self.logger.info(f"User '{self.username}' canceled the creation of a new project.")
AttributeError: 'CreateProjectPage' object has no attribute 'logger'
2024-05-31 01:43:47,995 - flet_runtime - INFO - Assets path configured: /Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/assets
2024-05-31 01:43:47,996 - flet_runtime - INFO - Starting up UDS server on /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/rC7xRw5CXm
2024-05-31 01:43:47,996 - flet_runtime - INFO - Flet app has started...
2024-05-31 01:43:47,996 - flet_runtime - INFO - App URL: /var/folders/r7/78p0xhg10fnfbsk_5lbgxwpc0000gn/T/rC7xRw5CXm
2024-05-31 01:43:47,996 - flet_runtime - INFO - Starting Flet View app...
2024-05-31 01:43:47,996 - flet_runtime - INFO - Flet View found in: /Users/soleymani/.flet/bin/flet-0.22.1
2024-05-31 01:43:48,283 - flet_runtime - INFO - App session started
2024-05-31 01:43:56,449 - __main__ - WARNING - Invalid login attempt for user: admin
2024-05-31 01:43:57,031 - __main__ - WARNING - Invalid login attempt for user: admin
2024-05-31 01:43:57,999 - __main__ - WARNING - Invalid login attempt for user: admin
2024-05-31 01:44:02,432 - __main__ - INFO - User 'admin' logged in successfully
2024-05-31 01:44:07,415 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=AttributeError("'CreateProjectPage' object has no attribute 'logger'")>
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/soleymani/Library/Python/3.9/lib/python/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "/Users/soleymani/Desktop/IUST/ap/newTrello/Trellomize-16/gui1.py", line 898, in cancel_dialog
    self.logger.info(f"User '{self.username}' canceled the creation of a new project.")
AttributeError: 'CreateProjectPage' object has no attribute 'logger'
